### ISSUE TITLE
To-Do App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by dobbykong** [dobbykong/Bare-Minimum-TODO#2]
### 만들고자 하는 기능이 무엇인가?
To-Do 추가 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가?
1. [ ] 내용을 입력할 input 추가
2. [ ] 입력한 내용을 추가할 add button 추가
3. [ ] input / button css 작성
