### ISSUE TITLE
To-Do App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by dobbykong** [dobbykong/Bare-Minimum-TODO#3]
### 만들고자 하는 기능이 무엇인가?
To-Do 목록 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가?
1. [ ] 추가된 To-Do 내용 체크 박스 추가
2. [ ] 추가된 To-Do 내용 수정 버튼 추가
3. [ ] 추가된 To-Do 내용 삭제 버튼 추가
4. [ ] To-Do 목록 css 작성

### 예상 작업 시간
3h
